### PR TITLE
README.md: Add a note for init and header name

### PR DESCRIPTION
**Pull request by bryanasdev000**
Just a little note to help anyone that uses it, since the project does not have a documentation, yet the mention to the init command helps compare mdbook config to mdzk, with special attention that without the head `[mdzk]` we get a:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unable to represent the item as a JSON Value

Caused by:
    unsupported None value', src/config.rs:63:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### CODE REVIEW

**Comment by ratsclub** [comment]
Thanks for the feedback. I guess we could implement a warning on this case!

**Comment by bryanasdev000** [comment]
> Thanks for the feedback. I guess we could implement a warning on this case!
  
Feel free to edit as you please, I just think that a note is good because I got the error when building my notes today with the latest version from nixpkgs.

**Comment by kmaasrud** [comment]
What does your `mdzk.toml` look like? I'm not able to reproduce the panic myself... Although there is an unwrap related to loading the config from a string, it should be pretty flexible and ignore unknown tables - as long as they are valid TOML. 

Panics should really not be documented, but rather considered bugs and removed ASAP

**Comment by ratsclub** [comment]
@kmaasrud I guess then problem occurs when one has `[book]` instead of `[mdzk]`.

**Comment by ratsclub** [comment]
@bryanasdev000 We are on our way to update the docs, so this situation might improve a lot in the future! We are handling this error on #41 too.

**Pull request closed without merging**
