### PR TITLE
New vision for mdzk

### PR DESCRIPTION
**Pull request by kmaasrud**
# Motivation

> **TL;DR:** With a focus on connected notes, this PR removes static site generation and wikilinks, improving CommonMark compatibility and flexibility in user workflows.

mdzk is all about _connected notes_. With this PR, I'm removing the static site generation feature from the tool, as there are already many static site generators available, and I believe mdzk can be more valuable as a focused, Unix-like command line tool.

Additionally, I'm removing support for wikilinks to improve compatibility with CommonMark. This will allow for more flexibility in user workflows, as many tools such as LSPs, syntax highlighters, and SSGs don't support wikilinks themselves. By adhering to CommonMark standards, users can more easily integrate their existing Markdown notes into mdzk.

Overall, these changes have resulted in a significant speedup of the tool---which is always welcome!

### CODE REVIEW

**Comment by ratsclub** [comment]
This seems like the way forward! Everything is working as expected here!

**Review by ratsclub — APPROVED** [review]

**Comment by edrex** [comment]
Hi, just a lurker popping up.

I've been keeping an eye on mdzk dev. I have a big markdown notes repo, densely connected via wikilinks. I utilize various tools when working with the repo (michael's zk, marksman, emanote, logseq, helix, emacs) and have a long-term back-burner project ([edrex/notes.env](https://github.com/edrex/notes.env)) to make a nix-based notes software "env" with well-tested workflows for capture/review/migration/linting/sync/publishing etc, as well as pre-commit-style automations, all accessible via shell or a top level terminal menu (using [Mange/tydra](https://github.com/Mange/tydra))

Anyway, just want to make sure: wikilinks are way out? The idea being to migrate them to standard markdown links? That's a valid choice, although I will be sticking with wikilinks (even though a migration would be straightforward) because I like to optimize for quick entry with basic text editing. Just curious, do you write `[other-note](other-note.md)`?

**Comment by kmaasrud** [comment]
Hi @edrex! I'm always happy to see lurkers exploring what is going on with mdzk :smile:

> Anyway, just want to make sure: wikilinks are way out? The idea being to migrate them to standard markdown links? That's a valid choice, although I will be sticking with wikilinks (even though a migration would be straightforward) because I like to optimize for quick entry with basic text editing.

We've been back and forth on this ever since the start, and it is a difficult design decision. My reasoning is that there are way to many assumptions about the users workflow that need to be done when using wikilinks. Most terminal users probably don't name their files with spaces (though possible), but they certainly want spaces in their titles sometime. Allright, enter aliases. But now we're suddenly in a state where we have deviated from the CommonMark standard to express something which could just as easily be expressed within the confines of the standard. 

Yes, it isn't difficult to keep a vault of files which have the same filename as title---that is how Obsidian solves it. But what about capitalization, plural form or other grammarly alterations? I found myself using aliases so often that the wikilink syntax did not make much sense anymore. 

> Just curious, do you write `[other-note](other-note.md)`? 

I would probably write `[Other note](other-note.md)` depending on the context, but yeah.

**Comment by edrex** [comment]
I tend to create files via link traversal with `CamelCase` filenames and hardly ever use aliases. Just habit from many years of wiki-ing, mostly with ikiwiki.

It's really problematic IMO how loosely many tools match wiki links to targets, often just looking for a substring match, ignoring directory structure, and then throwing an "ambiguous link" error when more than one file matches. If wikilinks are to persist in the ecosystem, which I think they are doomed to do as many tools support them, IMO what is needed for the format to mature is a living standard in the form of a spec and a CI test suite that tests all the various implementations against the spec and each other (so basically a commonmark extension), and gives visible red marks to all the implementations that have their own special flavor. The power of shame :grin:. That's yet another project I'll get around to eventually if someone else doesn't (prior discussion: https://github.com/artempyanykh/marksman/pull/117#issuecomment-1336635739).

**Comment by kmaasrud** [comment]
@edrex wholly agreed! Until that standard is made, I feel more comfortable not adding to the mess 😅

**Pull request merged**
